kafka:
  webapp:
    brokers: [127.0.0.1:9092]
  websocket:
    brokers: [127.0.0.1:9092]
    partition: 1
  prefix:
    chart: "CRT-"

redis:
  host: 127.0.0.1
  port: 6379
  trading:
    key: TRADING-RATE

zeromq:
  publisher: tcp://localhost:5563

sockjs:
  port: 18000
  path: /echo

tradingchart:
  quantity: 10
