kafka:
  webapp:
    brokers: [127.0.0.1:9092]
  websocket:
    brokers: [127.0.0.1:9092]
    partition: 1
  prefix:
    chart: "CRT."

redis:
  host: 127.0.0.1
  port: 6379
  trading:
    key: TRADING-RATE

zeromq:
  publisher:
    matching-engine: tcp://localhost:5563
    trading-broker: tcp://localhost:5564
  key:
    suffix:
      orderbook: :ORDER_BOOK
      openorder: :OPEN_ORDER
      orderhistory: :ORDER_HISTORY
      last24h: :LAST24H_TRANSACTION
      tradinghistory: :TRADING_HISTORY

sockjs:
  port: 18000
  path: /echo

tradingchart:
  quantity: 10
