db:
  host: 10.10.10.103
  port: 5432
  name: apidev
  username: appdev
  password: FdN94Ceb9DQH3hE9

kafka:
  webapp:
    brokers: [127.0.0.1:9092]
  websocket:
    brokers: [127.0.0.1:9092]
#    brokers: [10.11.12.28:9092]
    partition: 1
  prefix:
    chart: "CRT-"

redis:
  host: 127.0.0.1
  port: 6379
  trading:
    key: TRADING-RATE

zeromq:
  publisher:
    matching-engine: tcp://localhost:5563
    trading-broker: tcp://localhost:5564
  key:
    suffix:
      orderbook: :ORDER_BOOK
      openorder: :OPEN_ORDER
      orderhistory: :ORDER_HISTORY
      last24h: :LAST24H_TRANSACTION
      tradinghistory: :TRADING_HISTORY

sockjs:
  port: 18000
  path: /ws

tradingchart:
  quantity: 10
